# 2048 deployment and service
# Service

apiVersion: v1
kind: Service
metadata:
  name: twofour-service
  labels:
    app: twofour-service
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector: 
    app: twofour-game
  type: ClusterIP

---

# Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: twofour-game
spec:
  selector:
    matchLabels:
      app: twofour-game
  replicas: 1
  template:
    metadata:
      labels:
        app: twofour-game
    spec: 
      containers: 
      - name: 2048-container
        image: "blackicebird/2048"
        ports:
        - containerPort: 80

---

# Snake deployment and service
# Service

apiVersion: v1
kind: Service
metadata:
  name: snake-service
  labels:
    app: snake-service
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector: 
    app: snake-game
  type: ClusterIP

---

#Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: snake-game
spec:
  selector:
    matchLabels:
      app: snake-game
  replicas: 1
  template:
    metadata:
      labels:
        app: snake-game
    spec: 
      containers: 
      - name: snake-container
        image: "aschil/snake"
        ports:
        - containerPort: 80

---

# Ingress

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: twofoursnake-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: /twofour(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: twofour-service
            port:
              number: 80
      - path: /snake(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: snake-service
            port: 
              number: 80
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: snake-service
            port:
              number: 80
